### ISSUE TITLE
Notification Customization

### ISSUE THREAD

**Issue by SBerenji** [Sudhan-Dahake/CalamityCall#6]
I have been facing some challenges with customizing the Android notification to exactly match our design. The code for the standard notifications created is under branch "Notif_Saba" and XML files have been created based on the design.

**Comment by hsihak** [comment]
The issue has been addressed. Please try out the changes, and if they meet your expectations, feel free to close the issue. Thanks! ✨

**Comment by serb2341** [comment]
Issue has been fixed. The push notification background colours now match.
